client:
  certificate: ~
  client_cert: ~
  client_key: ~
  hosts:
    - "internal-elk-cluster-305311601.ap-southeast-1.elb.amazonaws.com"
  http_auth: ~
  master_only: false
  port: 9200
  ssl_no_validate: false
  timeout: 30
  url_prefix: ~
  use_ssl: false
logging:
  blacklist:
    - elasticsearch
    - urllib3
  logfile: /opt/curator/curator.txt
  logformat: default
  loglevel: INFO
